### ISSUE TITLE
Folders structure

### ISSUE THREAD

**Issue by mehdibo** [bkader/ci-gettext#1]
Why are you putting the files (libraries/helpers) inside the system folder? is this still working with CodeIgniter 3.1.7?

Nice job btw.

**Comment by bkader** [comment]
Hi there.  

You can put folders the way they are but I prefer putting them inside the application folder to avoid touching system/core folder.  This was made on CI **3.1.4** but I don't think there will be issues using it on the latest version.

This is kind of old library, you may want to use the hook instead: [CI-Gettext-Hook](https://goo.gl/yEhVhn).

**Comment by mehdibo** [comment]
Thanks! I'll check it out

**Comment by bkader** [comment]
You're very welcome **brother**.  
You may be interested in my [Theme Library](https://goo.gl/gIMfYw) as well ;).
